<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	 xmlns="http://www.ajbell.co.uk/schemas/xsd/businessModel/workflow/workflowAttributes.xsd"
	 targetNamespace="http://www.ajbell.co.uk/schemas/xsd/businessModel/workflow/workflowAttributes.xsd"
	 elementFormDefault="qualified"
	 attributeFormDefault="unqualified">
	<xs:element name="workflowAttributes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="caseDescription" minOccurs="0"/>
				<xs:element ref="caseNumber" minOccurs="0"/>
				<xs:element ref="stepDescription" minOccurs="0"/>
				<xs:element ref="stepName" minOccurs="0"/>
				<xs:element ref="startedBy" minOccurs="0"/>
				<xs:element ref="procedureName" minOccurs="0"/>
				<xs:element ref="addressee" minOccurs="0"/>
				<xs:element ref="arrivalDateTime" minOccurs="0"/>
				<xs:element ref="deadlineDateTime" minOccurs="0"/>
				<xs:element ref="timeinQueue" minOccurs="0"/>
				<xs:element ref="priority" minOccurs="0"/>
				<xs:element ref="urgent" minOccurs="0"/>
				<xs:element ref="opened" minOccurs="0"/>
				<xs:element ref="suspended" minOccurs="0"/>
				<xs:element ref="releasable" minOccurs="0"/>
				<xs:element ref="forwardable" minOccurs="0"/>
				<xs:element ref="lockedBy" minOccurs="0"/>
				<xs:element ref="history" minOccurs="0"/>
				<xs:element ref="delayedReleaseId" minOccurs="0"/>
				<xs:element ref="auditDescription" minOccurs="0"/>
				<xs:element ref="parentDelayedReleaseID" minOccurs="0"/>
				<xs:element ref="parentCaseNumber" minOccurs="0"/>
				<xs:element ref="parentProcedureName" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="caseDescription" type="xs:string"/>
	<xs:element name="caseNumber" type="xs:int"/>
	<xs:element name="stepDescription" type="xs:string"/>
	<xs:element name="stepName">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="8"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="startedBy" type="xs:string"/>
	<xs:element name="procedureName">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="8"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="addressee" type="xs:string"/>
	<xs:element name="arrivalDateTime" type="xs:dateTime"/>
	<xs:element name="deadlineDateTime" type="xs:dateTime"/>
	<xs:element name="timeinQueue" type="xs:duration"/>
	<xs:element name="priority" type="xs:string"/>
	<xs:element name="urgent" type="xs:boolean"/>
	<xs:element name="opened" type="xs:boolean"/>
	<xs:element name="suspended" type="xs:boolean"/>
	<xs:element name="releasable" type="xs:boolean"/>
	<xs:element name="forwardable" type="xs:boolean"/>
	<xs:element name="lockedBy" type="xs:string"/>
	<xs:element name="history" type="xs:string"/>
	<xs:element name="delayedReleaseId" type="xs:string"/>
	<xs:element name="auditDescription" type="xs:string"/>
	<xs:element name="parentDelayedReleaseID" type="xs:string"/>
	<xs:element name="parentCaseNumber" type="xs:int"/>
	<xs:element name="parentProcedureName" type="xs:string"/>
</xs:schema>